package com.vaadin.example.ui.weather;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.example.weather.dto.WeatherData;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 *
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class WeatherDisplayDesign extends VerticalLayout {
    protected Label temperature;
    protected Label shortSummary;
    protected Label longSummary;
    protected Grid<WeatherData> grid;

    public WeatherDisplayDesign() {
        Design.read(this);
    }
}
